"""Rule and Notification tables

Revision ID: d463cfab320f
Revises: e09451d22dc2
Create Date: 2026-09-22 17:22:22.557088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd463cfab320f'
down_revision: Union[str, Sequence[str], None] = 'e09451d22dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.alter_column('notification_logs', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('notification_logs_rule_id_fkey'), 'notification_logs', type_='foreignkey')
    op.drop_column('notification_logs', 'channel')
    op.drop_column('notification_logs', 'title')
    op.drop_column('notification_logs', 'symbol')
    op.add_column('rules', sa.Column('last_state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'last_state')
    op.add_column('notification_logs', sa.Column('symbol', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('notification_logs', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('notification_logs', sa.Column('channel', postgresql.ENUM('IN_APP', 'EMAIL', name='notificationchannel'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notification_logs_rule_id_fkey'), 'notification_logs', 'rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notification_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notification_logs', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_notification_channels_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
